apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa.dev.web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep.dev.web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50